### ISSUE TITLE
Выпустить версию 2.0

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/simple-refal#134]
Давно пора двигать `master`.

Предлагается для версии 2.0 реализовать корректную работу front-end’а Рефала-5λ, т.е. должны быть реализованы все встроенные функции Рефала-5 (#102), а также должны поддерживаться синтаксические расширения (#51, #94).

* [x] #102 Проектирование и разработка библиотеки встроенных функций Рефала-5λ
* [x] #94 Синтаксис Рефала-5λ
* [x] #51 Front-end расширенного РЕФАЛа-5
* [x] #125 Уточнить цели проекта

Что не будет входить в версию 2.0:
* Динамическая загрузка модулей (#76)
* Задачи, не входящие в веху «Рефал-5λ»:
  * Поддержка Юникода (#27)
  * Оптимизированная компиляция условий (#17)
  * Прогонка и специализация функций (#91, #122, #126)
  * Улучшенная оптимизация образцовых выражений (#15)
* Поддержка вычислений с метакодом РЕФАЛа-5 (`Freeze`, `Freezer`, `Dn`, `Up`, `Ev-met`).
* Поддержка XML РЕФАЛа-5 (`XMLParse`).

**Comment by Mazdaywik** [comment]
<https://github.com/bmstu-iu9/simple-refal/releases/tag/2.0>
