### ISSUE TITLE
Синтаксис Рефала-5λ

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/simple-refal#94]
Эта задача — подзадача для #51.
Эта задача — подзадача для #134.

# Подытоживая
**(Добавлено 2017-12-04)** Требуется реализовать следующие средства:

* [x] Классический и расширенный режимы (#144).
* [x] Функции высших порядков (#114).
* [x] Расширенный синтаксис блоков (#113).
* [x] Присваивания (#113).
* [x] Блоки (включая функции) с пустым телом.
* [x] Определения `$ENUM`, `$EENUM`, `$SWAP`, `$ESWAP`.
* [x] Поддержка включения файлов (`$INCLUDE`, #92).
* [x] Нативные вставки (#115).
* [x] `$SCOPEID` (сделано для Простого Рефала в задаче #135, но её переоткрывать не буду).
* [x] `$EASTEREGG`.
* [x] Сокрытия переменных.
* [x] Абстрактные типы данных.

Реализация ключевых слов `$INLINE` и `$SPEC` будет реализована в ходе выполнения соответствующих задач (#91, #122, #126). Здесь (т.е. в #134) она не нужна.

# Синтаксическая сводка
Синтаксис ниже дан в нотации Вирта
```
Program = ProgramElement*.
ProgramElement =
    Include
  | Declaration
  | SimpleDefinition
  | ForceEntry
  | Function
  | NATIVE-INSERTION
  | ";"
  .
Include = "$INCLUDE" COMPOUND ";".
Declaration = (ExternKeyword | "$FORWARD") NameList.
ExternKeyword = "$EXTERN" | "$EXTRN" | "$EXTERNAL".
SimpleDefinition = ("$ENUM" | "$EENUM" | "$SWAP" | "$ESWAP") NameList.
ForceEntry = "$ENTRY" NameList.
NameList = NAME {"," NAME} ";"

Function = ["$ENTRY" | "$INLINE" | "$SPEC" ] NAME Block.
Block = "{" (Sentences | NATIVE-INSERTION) "}".
Sentences = [ Sentence {"," Sentence} [";"] ].
Sentence =
  Pattern
  { Condition | Assignment }
  ( "=" ResultEx | "," ResultEx ":" Block ).
Condition = "," ResultEx ":" Pattern.
Assignment = "=" ResultEx ":" Pattern.
ResultEx = Result {":" Block}.

Pattern = PatternTerm*.
PatternTerm =
    Atom | "(" Pattern ")" | "[" NAME Pattern "]" | VARNAME ["^"].
Result =
    Atom | "(" Result ")" | "[" NAME Result "]" | VARNAME
  | OpenCall Result ">"
  .
OpenCall = "<" NAME | "<" | "<+" | "<-" | "<*" | "</" | "<%" | "<?".
Atom = NUMBER | CHAR | COMPOUND | Identifier | FuncPtr.

Identifier = NAME.
FuncPtr = "&" NAME.
```
# Лексические детали
Поддерживаются три вида комментариев: комментарии языка Си `/*…*/`, комментарии Си++ `//…` и классические комментарии Рефала — знак `*` в начале строки.

И небольшие пояснения по поводу каждому из лексических доменов, написанных БОЛЬШИМИ буквами в грамматике.

* `NATIVE-INSERTION` — вставка кода на Си++, подробно описаны в #11.
* `COMPOUND` — последовательность символов, заключённая в двойные кавычки. В директиве `$INCLUDE` задаёт имя включаемого файла (так удобнее будет делать и синтаксический анализ, и разбор в SRMake), в роли атома представляет собой идентификатор — составной символ (см. новый синтаксис РЕФАЛа-5 в файле NEWS.TXT дистрибутива).
* `NAME` — имя, играет роль имени функции и идентификатора. Может начинаться с любой буквы или подчёркивания, после которой может следовать любое количество букв, цифр, дефисов и подчёркиваний. При этом дефисы и подчёркивания _не эквивалентны_.
* `NUMBER` — десятичное целое число от 0 до 2<sup>32</sup>−1.
* `CHAR` — литеральный символ ASCII, заключён в одинарные кавычки, может содержать escape-последовательности Си. Несколько символов подряд могут быть записаны подряд внутри одной пары кавычек (`'a' 'b' 'c' '\n'` == `'abc\n'`). Поведение двух одинарных кавычек подряд не определено.

# Отличия от РЕФАЛа-5
Описанный синтаксис, как можно видеть, является точным надмножеством РЕФАЛа-5 (нового синтаксиса). Поэтому все отличия являются его расширениями. Все их здесь перечислять не будем (особенно, ещё не реализованные), но заметим, что самое важное — это первоклассные функции (указатели на глобальные функции, вложенные безымянные функции и косвенный вызов).

# Отличия от Простого Рефала
Предлагаемый язык не является точным синтаксическим надмножеством Простого Рефала, поскольку в последнем идентификаторы должны помечаться знаком `#`, а указатели на функции записываются просто как имя функции. В нём последние два правила выглядели бы как
```
Identifier = "#" NAME.
FuncPtr = NAME.
```
Остальные элементы синтаксиса являются точным надмножеством. С точки зрения семантики — Рефал-5λ является точным _семантическим_ надмножеством Простого Рефала.

# Реализация
Лексику Рефала-5λ можно считать точным надмножеством лексики _задокументированного_ РЕФАЛа-5 (в исходниках компилятора можно найти много всяких чудес вроде имён и чисел, ограниченных знаками `.` в начале и конце), либо _почти точным_ надмножеством Простого Рефала (не используется знак `#`, знаки `-` и `_` в именах эквивалентны). Этот факт будем учитывать в дальнейших рассуждениях.

Синтаксический анализ (включая лексику) можно реализовать следующими методами:
* написать с нуля,
* расширить готовый front-end из проекта [Mazdaywik/5-to-basis](https://github.com/Mazdaywik/5-to-basis),
* расширить, слегка изменив, готовый front-end непосредственно из Простого Рефала.

Первый вариант логично исключить, поскольку нет нужды писать новый парсер с нуля, когда есть неплохие заготовки.

Второй вариант неплох (и очень неплох) — проект [5-to-basis](https://github.com/Mazdaywik/5-to-basis) имеет качественный синтаксический анализатор, выдающий ясные сообщения об ошибках. При этом координаты синтаксических ошибок включают в себя помимо номера строки ещё и номер колонки. Недостатки подхода, однако, следующие:
* Синтаксическое дерево порождается в другом формате, его надо будет адаптировать.
* Написан, ага, на РЕФАЛе-5. Проблема курицы и яйца. Решается это тем, что сам проект 5-to-basis предназначен для конвертирования полного РЕФАЛа-5 в его подмножество Базисного Рефала (которое семантически общее с Простым Рефалом). Немного перенастроив back-end, можно получить совместимые исходники.
* Недостающие конструкции: вложенные функции (но есть нетерминал Block), пустые функции и статические ящики (делаются из директив extern), присваивания (делаются по аналогии с условиями), указатели на функции.

Третий вариант сравним со вторым. Основное преимущество: заготовка парсера уже есть в проекте и написана на Простом Рефале. Недостатки:
* Основной: не является точным подмножеством. Эту проблему нужно как-то решать (см. ниже).
* Недостающие конструкции: условия, блоки, ключевые слова `$EXTRN` и `$EXTERNAL`, скоропись для некоторых стандартных функций (`<+…>` и другие).

Варианты решения проблемы:
* Уровень лексера. Для режима Рефала-5λ лексический анализатор выдаёт `TkNameR5`, для Простого Рефала — `TkNameSR`. Соответственно, парсер связывает с `&` только первый, с `#` только второй, одинокий знак в выражении по-разному интерпретирует (как идентификатор или как указатель на функцию соответственно). В остальных контекстах они интерпретируются одинаково.
* Уровень парсера. Прокидываем флаг режима компиляции. Он будет передаваться из функции в функцию, учитываться будет только на этапе распознавания выражений (образцов и результатов).
* Проход после парсера. Строим синтаксическое дерево, в котором будут предусмотрены три разных узла для конструкций вида `NAME`, `"#" NAME` и `"&" NAME`. Отдельным проходом в зависимости от режима преобразуем первый элемент в идентификатор или имя функции, один из двух других — тоже в идентификатор или имя функции, на оставшийся выдаём синтаксическую ошибку.
* Отказаться от поддержки front-end’а Простого Рефала, единовременно перейдя на подмножество Рефала-5λ — вставив куда надо `&` и удалив везде `#`.
* Реализовать сначала поддержку включения файлов (#92). В исходном парсере в точке, где происходит анализ неоднозначной конструкции, вызывать новую функцию (назовём её `<InputDialect>`). Исходный парсер поместить в заголовочный файл, который подключать из двух единиц трансляции, где функция `<InputDialect>` реализована по-разному. Так можно избежать протягивания через весь рекурсивный спуск флага режима.
* Разрешить в Рефале-5λ необязательный знак `#` перед идентификаторами, в Простом Рефале — знак `&` перед указателями на функцию (за исключением имён сразу после `<`). В этом случае корректная программа на Простом Рефале с проставленными знаками `&` будет корректной программой на Рефале-5λ (за исключением некоторых деталей). Такое можно разрешить, по крайней мере, на переходный период.

В общем, нужно будет выбрать между вторым вариантом и третьим, и если будет выбран третий вариант — выбрать способ решения проблемы несовместимости.

**Comment by Mazdaywik** [comment]
Мне больше понравился второй вариант. Он сразу даст готовый front-end для «задокументированного» подмножества РЕФАЛа-5, после чего можно будет называть сей проект Рефалом-5λ совершенно честно. Затем его можно будет постепенно расширять как возможностями Простого Рефала (начать следует с функций высших порядков включая вложенные функции), так и недокументированными фичами лексера и парсера РЕФАЛа-5 (типа записи escape-последовательностей вне кавычек).

Вопрос в «квантовом скачке» нулевого шага раскрутки предлагается решить так. Перенастроить проект «5-to-basis» таким образом, чтобы он на выходе порождал корректный код Простого Рефала и затем вызывать его как препроцессор.
* На первом этапе функцией `<System …>` тупо вызывать `refgo`, порождая временный файл и обрабатывая его известным путём далее.
* На втором этапе (который нужно будет после тестов тут же сохранить в стабильную версию) препроцессор уже можно будет скомпилировать вместе с основным набором исходников, при этом выход препроцессора (текст программы) напрямую передавать в `LexFolding` минуя временный промежуточный файл.

Затем уже можно будет проводить рефакторинг, устраняя избыточные стадии между, конвертируя одно AST в другое, а потом и вовсе научить парсер РЕФАЛа-5 порождать AST Простого Рефала, а обработку блоков и условий перенести на стадию обессахаривателя.

При этом можно независимо расширять front-end Простого Рефала, дополнив его, например, условиями или блоками.

**Comment by Mazdaywik** [comment]
Подытоживая. Требуется реализовать следующие средства:

* [ ] Определения `$ENUM`, `$EENUM`, `$SWAP`, `$ESWAP`.
* [ ] Поддержка включения файлов (`$INCLUDE`).
* [ ] Блоки (включая функции) с пустым телом.
* [ ] Расширенный синтаксис блоков (#113).
* [ ] Присваивания (#113).
* [ ] Функции высших порядков (#114).
* [ ] Нативные вставки (#115).

Реализация ключевых слов `$INLINE` и `$SPEC` будет реализована в ходе выполнения соответствующих задач (#91, #122, #126). Здесь (т.е. в #134) она не нужна.

**Comment by Mazdaywik** [comment]
Комментарии C++ я решил не поддерживать. Если интересно, я потом могу их добавить, а пока они избыточны.
